### PR TITLE
Fix on form

### PR DESCRIPTION
**Pull request by MarvinCrepin**

### CODE REVIEW

**Comment by MarvinCrepin** [comment]
cant pr because of grump

**Comment by rocambille** [comment]
> cant pr because of grump

no, because of you :)

just fix the error https://github.com/WildCodeSchool/reims-202109-php-project3-marche-conclu/runs/4546139678?check_suite_focus=true

**Comment by MarvinCrepin** [comment]
i cant give an User object it recognize it as a simple object

**Comment by rocambille** [comment]
you're not giving a User object, you're giving a simple object. that's the point...

**Comment by MarvinCrepin** [comment]
how can i get a "user object" it always give me simple object and when i dd it i weirdly have an user object but grump is not saying the same thing

**Pull request merged**
